name: Tests

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - '**'
env:
  DIR_TESTS: /tmp/tests-smart-table
  REP_TESTS: https://github.com/Yandex-Practicum/tests-smart-table.git
  REPO: ${{ github.event.repository.name }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Set up GitHub Actions
      uses: actions/checkout@v5
      with:
        path: smart-table
    - name: Use Node.js 24.x
      uses: actions/setup-node@v5
      with:
        node-version: 24.x
    - name: Install dependencies
      run: cd smart-table && npm ci
    - name: Build project
      run: cd smart-table && npm run build
    - name: Get testing lib
      run: set -eu && git clone --depth 1 $REP_TESTS $DIR_TESTS
    - name: Run tests
      run: bash $DIR_TESTS/bin/run.sh
